version: '2.2'
services:
  web:
    build:
      context: .
      dockerfile: ../dockerfile
    ports:
      - 80:80
    volumes:
      - ../mtg_wintercms-theme/demo:/var/www/html/themes/demo
      - ../builder:/var/www/html/plugins/winter/builder
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_DATABASE=stage
      - DB_USERNAME=root
      - DB_PASSWORD=root
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stage