list: $/melvin/mtgmoney/models/autocomplete/columns.yaml
modelClass: Melvin\Mtgmoney\Models\Autocomplete
title: Autocomplete
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'melvin/mtgmoney/autocomplete/update/:id'
