list: $/melvin/mtgmoney/models/cards/columns.yaml
modelClass: Melvin\Mtgmoney\Models\Cards
title: Cards
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'melvin/mtgmoney/cards/update/:id'
