list: $/melvin/mtgmoney/models/mtgjson/columns.yaml
modelClass: Melvin\Mtgmoney\Models\MTGJson
title: MTGJson
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'melvin/mtgmoney/mtgjson/update/:id'
